# Generated by Django 4.0 on 2022-01-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snipped',
            field=models.CharField(default='Read more...', max_length=255),
        ),
    ]
